- name: Install sudo package
  ansible.builtin.package:
    name: "{{ sudo_requirements }}"
    state: present

- name: Create sudoers.d directory
  ansible.builtin.file:
    path: "{{ sudo_sudoersd_path }}"
    owner: "{{ sudo_sudoersd_owner }}"
    group: "{{ sudo_sudoersd_group }}"
    state: directory
    mode: 0755

- name: Include sudoers.d directory
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^[#@]includedir .*"
    line: "#includedir {{ sudo_sudoersd_path }}"
    owner: "{{ sudo_sudoersd_owner }}"
    group: "{{ sudo_sudoersd_group }}"
    validate: visudo -cf %s
    mode: 0440

- name: Create sudoers files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ sudo_sudoersd_path }}/{{ item.name }}"
    owner: "{{ sudo_sudoersd_owner }}"
    group: "{{ sudo_sudoersd_group }}"
    validate: visudo -cf %s
    mode: 0440
  loop: "{{ sudo_files }}"
  loop_control:
    label: "{{ sudo_sudoersd_path }}/{{ item.name }}"
