- name: Converge
  hosts: all
  vars:
    sudo_files:
    - name: 10-molecule
      content: |
        molecule ALL=(ALL) NOPASSWD: ALL

  pre_tasks:
  - name: Update cache (debian)
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 800
    changed_when: false

  - name: Create molecule user
    ansible.builtin.user:
      name: molecule
      state: present

  roles:
  - dudecalledbro.sudo
